#!/usr/bin/perl -w
# prereq: apt install libnet-openssh-perl libio-pty-perl
my $version = "1.0";
use strict;
use warnings;
use Getopt::Long;
use POSIX "setsid";
use Net::OpenSSH;
use JSON::XS;


my $host;
my $username = 'root';
my $password;
my $port = 22;
my $ips;

my %opt = (
                "help" => 0,
        );


# Gather the options from the command line
GetOptions(\%opt,
                'host=s' => \$host,
                'user=s' => \$username,
                'pass=s' => \$password,
                'port=i' => \$port,
                'ips=s' => \$ips,
                'help',
        );


my %args = (
  user      => $username,
  password  => $password,
  port      => $port,
  autodie   => 0,
  timeout   => 10,
  autoflush => 1,
);


sub usage {
        # Shown with --help option passed
        print "\n".
                "   addmoreips $version - Adds more ips to the target server\n".
                "   Bug reports, feature requests\n".
                "   Created by e1z0 (e1z0\@icloud.com)\n".
                "\n".
                "   Options\n".
                "      --host       Remote machine host\n".
                "      --user       Remote machine ssh username\n".
                "      --pass       Remote machine ssh password\n".
                "      --port       Remote machine port (Default 22)\n".
                "      --ips        Ips that should be added\n".
                "\n";
        exit;
}


sub suffix_iprange {
my ($ipai) = @_;
my @ips;

# if it's /24 subnet
if ($ipai =~ m/\/24/) {
  my @subas = split /\./, $ipai;
  my $subnet = "$subas[0].$subas[1].$subas[2]";
  print "Detected /24 subnet: $subnet\n";
  for (my $i = 1; $i < 255; $i++) { # x.x.x.1-x.x.x.254
    push @ips, "$subnet.$i";
  }
}

# if it's range
if ($ipai =~ m/-/) {
  my @split = split(/-/, $ipai);
  my @subas1 = split /\./, $split[0];
  my @subas2 = split /\./, $split[1];
  my $from = $subas1[3];
  my $to = $subas2[3];
  my $subnet = "$subas1[0].$subas1[1].$subas1[2]";
  print "Detected ip range from: $subnet.$from to: $subnet.$to\n";
  for (my $i = $from; $i < $to+1; $i++) { # x.x.x.1-x.x.x.254
    push @ips, "$subnet.$i";
  }
}

# if it's single addresses
if ($ipai =~ m/ /) {
print "Detected single addresses\n";
@ips = split / /, $ipai;
}


if (scalar(@ips) == 0) {
  my $serv->{respond} = "We are unable to generate list of the ip addresses maybe you where using wrong syntax to specify ip addresses/ranges/etc..";
  $serv->{error} = 1;
  my $json = encode_json($serv);
  print "JSON: $json\n";
  exit(12);
}

return @ips;
}


sub enable_service {
  my ($file,$ssh) = @_;
  my $optz={recursive => 1, glob => 1, timeout => 1000, quiet => 0,stderr_to_stdout => 1};
  # transmit file
  $ssh->scp_put($optz, $file,"/usr/local/bin/addips");
  # transmit service
  my $out = $ssh->system("rm /etc/systemd/system/addips.service;chmod +x /usr/local/bin/addips &&".
  "echo -e \"[Unit]\nDescription=ips addition\nAfter=network-online.target\n\n[Service]\nType=simple\nUser=root\nGroup=root\nWorkingDirectory=/usr/bin\nPermissionsStartOnly=true\nExecStart=/usr/local/bin/addips\n\n[Install]\nWantedBy=multi-user.target\" >> /etc/systemd/system/addips.service &&".
  "systemctl enable addips");
  print "Got output: $out\n";
  # execute addition instantly
  #my $out2 = $ssh->system("/usr/local/bin/addips &");
  unlink $file;
  return 1;
}

sub add {
  my ($iface,$ssh) = @_;
  my @ip = suffix_iprange($ips);
  my $uuid = `cat /proc/sys/kernel/random/uuid`;
  chomp($uuid);
  my $file = "/tmp/$uuid";
  print "Got filename: $file\n";
  open(FH, '>', $file) or print "error";
  print FH "\#/bin/sh\n";
  foreach ( @ip ) {
    print FH "ip addr add $_/24 dev $iface\n";
  }
  close(FH);
  if (enable_service($file,$ssh)) {
    return 1; # 1->ok, 0->err
  } else {
    my $serv->{respond} = "Unable to enable the service on the remote server";
    $serv->{error} = 1;
    my $json = encode_json($serv);
    print "JSON: $json\n";
    exit(12);
  }

}

if (defined($host)&&defined($username)&&defined($password)&&defined($port)&&defined($ips)) {
  # hack
  system('ssh-keygen -f "'.$ENV{"HOME"}.'/.ssh/known_hosts" -R '.$host);
  print "Connecting to server: $host\n";
  my $ssh;
  if ($password eq "key") {
    $ssh = Net::OpenSSH->new(host=>$host, user=>$username,
                port=>$port,
                key_path => '~/.ssh/id_rsa',master_opts => [-o => "StrictHostKeyChecking=no"]);

  } else {
    $ssh = Net::OpenSSH->new("$username:$password\@$host:$port",master_opts => [-o => "StrictHostKeyChecking=no"], timeout => 30);
  }
   my $res = $ssh->error;
   chomp $res;
   if ($ssh->error) {
     # UNABLE TO CONNECT
     print "Unable to connect to $host!\n";
     my $serv->{respond} = "Unable to connect to $host error: ".$ssh->error;
     $serv->{error} = 1;
     my $json = encode_json($serv);
     print "JSON: $json\n";
     exit(12);
   } else {
     # CONNECTED
     print "Connected\n";
     # collect some data
     my ($multi, $err) = $ssh->capture2("ip route get 8.8.8.8 | awk -- '{printf \$5}'");
     if ($err) {
       # collect failed
       my $serv->{respond} = "Unable to query default network interface name, ip tools package is not installed err: ".$ssh->error;
       $serv->{error} = 1;
       my $json = encode_json($serv);
       print "JSON: $json\n";
       exit(12);
     } else {
       # collect ok
       chomp($multi);
       print "Detected default network interface: $multi\n";
       if (add($multi,$ssh)) {
         my $serv->{respond} = "Everything seems to be went ok";
         $serv->{error} = 0;
         my $json = encode_json($serv);
         print "JSON: $json\n";
         exit(0);
       } else {
         print "Unexpected error...\n";
         exit(12);
       }
     }
   }

#   my ($multi, $err) = $ssh->capture2("hostname -I");
#   my @values = split(' ', $multi);
#   my $ipcount = 0;
#   foreach my $val (@values) {
#       next if ($val =~ /127.0.0/);
#       next if ($val =~ /:/);
#       $ipcount++;
#       # only add valid ip addresses to the list
#       push @ips, $val;
#   }




#my $serv->{respond} = "very good";
#$serv->{error} = 0;
#my $json = encode_json($serv);
#print "JSON: $json\n";
#exit(12);
} else {
if (defined $opt{'help'} && $opt{'help'} == 1) { usage(); }
print "You must provide the correct parameters for this application\n";
exit(15);
}
