#!/usr/bin/perl -w
# apt install libio-socket-portstate-perl
use strict;
use warnings;
use DBI;
use Data::Dumper;
use IO::Socket::PortState qw(check_ports);
use Net::IP;
my $dbh;
my %env; # variable to put laravel settings in
my %settings = ();


sub check_port {
my ($host,$port) = @_;
my $socket = IO::Socket::INET->new(PeerAddr => $host , PeerPort => $port , Proto => 'tcp' , Timeout => 3);
    #Check connection
    if( $socket )
    {
        return 0;
    }
    else
    {
        return 1;
    }

}

sub mark_server {
my ($id, $situation) = @_;
my $sta = $dbh->prepare("update sending_servers set status = ? where id = ?");
$sta->execute($situation,$id);
}

sub check_rbl {
my ($id,$ipas) = @_;
# dig +short 85.237.226.41.zen.spamhaus.org @1.1.1.1
my $ip = new Net::IP($ipas,4);
my $tmpa = $ip->reverse_ip();
my @rev = split /in/, $tmpa;
my $reverse = $rev[0]."zen.spamhaus.org";
print "IP: $ipas reverse ip: $reverse\n";
my $res = `dig +short $reverse \@1.1.1.1`;
if ($res =~ /127/gm) {
print "IP: $ipas is blacklisted on spamhaus!\n";
mark_server($id,"inactive");
}
}

sub check_servers {
# schedule type
my ($type) = @_;
my $sth = $dbh->prepare("select id,host,smtp_port as port from sending_servers");
$sth->execute();
my $count = 0;
my $arr = $sth->fetchall_arrayref({});
for my $server (@$arr) {
next if ($server->{host} eq "localhost");
$count++;
#print "Checking server ".$server->{host}."\n";
check_rbl($server->{id},$server->{host});
#print "connecting to: $server->{host}\n";
#if (check_port($server->{host},$server->{port})>0) {
#mark_server($server->{id},"inactive");
#} else {
#mark_server($server->{id},"active");
#}
#push(@results, "\'" . $row1[0] . "\'");
}
#if (@results) {
#my $formated = join(",",@results);
#my $raw = $dbh->prepare("UPDATE subscribers set status = '$status' WHERE id IN ($formated)");
#$raw->execute();
#}
#print "Res: $formated\n";
print "Servers affected: $count\n";
}



sub read_lavonelis {
# example $env{DB_PASSWORD}
open INI, $ENV{"HOME"}."/public_html/.env"||die "Neatidarau lavonelio aplinkos failo :(\n";
while (<INI>) {
chomp;
if (/^\W*(\w+)=?(\w.+)\W*(#.*)?$/) {
my $setting = $1; # setting
#chomp($setting);
my $value = $2; # value
$env{$setting} = $value;
} # end if regex
} # end while
close INI;
} # end read lavonelis

sub dbconn {
$dbh = DBI->connect("DBI:mysql:".$env{DB_DATABASE}.":".$env{DB_HOST}, $env{DB_USERNAME}, $env{DB_PASSWORD} ,{ PrintError => 1, RaiseError => 0 }) or die "Unable to connect to MySQL\n";
}

read_lavonelis();
dbconn();

if (defined($ARGV[0]) && $ARGV[0] > 0) {
check_servers($ARGV[0]);
}
