#!/usr/bin/perl -w
die;
reikia sutvarkyti
use strict;
use warnings;
use DBI;
my %env;
my $dbh;
my $run_mode = 1;

sub read_lavonelis {
# example $env{DB_PASSWORD}
open INI, $ENV{"HOME"}."/public_html/.env"||die "Neatidarau lavonelio aplinkos failo :(\n";
while (<INI>) {
chomp;
if (/^\W*(\w+)=?(\w.+)\W*(#.*)?$/) {
my $setting = $1; # setting
#chomp($setting);
my $value = $2; # value
$env{$setting} = $value;
} # end if regex
} # end while
close INI;
} # end read lavonelis
read_lavonelis();

sub dbconn {
$dbh = DBI->connect("DBI:mysql:".$env{DB_DATABASE}.":".$env{DB_HOST}, $env{DB_USERNAME}, $env{DB_PASSWORD} ,{ PrintError => 1, RaiseError => 0 }) or die "Unable to connect to MySQL\n";
}

sub stdin_question {
    my ($options,$text,$match) = @_;
    my $input;
    my $flag = 0;
    my @valid_options;
    if (!defined($options)) {
        $options = "yes,no";
    }
    if (!defined($text)) {
        $text = "(yes or no) :";
    }
    if (!defined($match)) {
        $match = 0;
    }
    @valid_options = split/,/, $options;
    while ($flag ne 1) {
        print $text;
        $input = <stdin>;
        chomp $input;
        foreach (@valid_options) {
            if (/$input/i) {
                if ($match eq 1) {
                    if (length($_) eq length($input)) {
                        $flag = 1;
                    }
                } else {
                    $flag = 1;
                }
            }
        }
    }
    return lc $input;
}

if (defined($ARGV[0])) {
$run_mode = 2;
}

if (`id -u` == 0) {
print "You are in root mode, this script will restart some services, to drop some system loads\n";
#if (stdin_question('y,n','Do you want to proceed ? (Y)es (N)o') =~ /y/) { 
system("/etc/init.d/mysql restart");
print "Done restarting mysql\n";
system("/etc/init.d/php-fpm restart");
print "Done restarting php-fpm\n";
system("/etc/init.d/nginx restart");
print "Done restarting nginx\n";
#}
} else {
print "You are in user mode, this script will try to cleanup mysql/queue, clear temp files and delete the caches\n";
#if (stdin_question('y,n','Do you want to proceed ? (Y)es (N)o') =~ /y/) {
# cleanup files in user mode
print "We are searching for temporary files and cleaning them out...\n";
system("find \$HOME/public_html/storage/app/keys -type f -exec rm {} \\;");
print "Done cleaning files!\n";
# cleanup mysql
print "Cleaning mysql...\n";
dbconn();
# clean jobs
my $sth1 = $dbh->prepare("DELETE FROM failed_jobs");
$sth1->execute();
my $sth2 = $dbh->prepare("DELETE FROM jobs");
$sth2->execute();
my $sth3 = $dbh->prepare("DELETE FROM system_jobs");
$sth3->execute();
print "Done cleaning mysql!\n";
# clean artisan caches
print "Cleaning laravel...\n";
system("cd \$HOME/public_html&&php artisan config:cache&&php artisan queue:flush&&php artisan cache:clear&&php artisan route:clear&&php artisan clear-compiled&&php artisan view:clear&&php artisan optimize");
print "All done!\n";
#}
}
