[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx/access.log
stderr_logfile=/var/log/nginx/error.log

[program:php-fpm]
command=/usr/sbin/php-fpm7.2 -F
autostart=true
autorestart=true
stdout_logfile=/var/log/php-fpm.log
stderr_logfile=/var/log/php-fpm-error.log

[program:laravel-queue-high]
command=/usr/bin/php7.2 -q /home/app/public_html/artisan queue:work --queue=high,default
autostart=true
autorestart=true
stdout_logfile=/home/app/public_html/storage/logs/queue-high.log
stderr_logfile=/home/app/public_html/storage/logs/queue-high-error.log

[program:laravel-schedule]
command=/bin/bash -c "while true; do /usr/bin/php7.2 -q /home/app/public_html/artisan schedule:run >> /dev/null 2>&1; sleep 60; done"
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null
