#!/usr/bin/php
<?php
if ($argv[1] == "") {
echo "Please provide a email for the first parameter of this script\n";
exit;
}
require("settings.php");

// just for later work
function post_request($url, array $params) {
  $query_content = http_build_query($params);
  $fp = fopen($url, 'r', FALSE, // do not use_include_path
    stream_context_create([
    'http' => [
      'header'  => [ // header array does not need '\r\n'
        'Content-type: application/x-www-form-urlencoded',
        'Content-Length: ' . strlen($query_content)
      ],
      'method'  => 'POST',
      'content' => $query_content
    ]
  ]));
  if ($fp === FALSE) {
    fclose($fp);
    return json_encode(['error' => 'Failed to get contents...']);
  }
  $result = stream_get_contents($fp); // no maxlength/offset
  fclose($fp);
  return $result;
}

// another example
function post_request2() {
echo file_get_contents('https://www.server.com', false, stream_context_create([
    'http' => [
        'method' => 'POST',
        'header'  => "Content-type: application/x-www-form-urlencoded",
        'content' => http_build_query([
            'key1' => 'Hello world!', 'key2' => 'second value'
        ])
    ]
]));
}

// prod
function get_storage_obj($emails) {
global $api, $key;

$url = "http://".$api."/api/v1/mails/getmulti";
echo "Opening connection to $url\n";
echo "Posting $emails\n";
$json = file_get_contents($url, false, stream_context_create([
    'http' => [
        'method' => 'POST',
        'header'  => "Content-type: application/x-www-form-urlencoded\nAuthorization: $key",
        'content' => $emails,

    ]
]));
return json_decode($json);
}

require_once("settings.php");
//$email = $argv[1];
$argai = array();
$count = 0;
foreach ($argv as $argas) {
if ($count >0) $argai[] = $argas;
$count++;
}
echo "Testing quering for emails ".print_r($argai,true)."\n";
$emails = json_encode($argai);
$obj = get_storage_obj($emails);
//foreach ($obj as $item) {
//print "Email: ".$item["email"]." has mx: ".$item["mx"]."\n";
//}
print_r($obj);
?>
